FROM dart:stable AS build

# Install flutter sdk
RUN apt-get install -y curl git unzip
RUN git clone https://github.com/flutter/flutter.git -b stable /flutter
ENV PATH="/flutter/bin:/flutter/bin/cache/dart-sdk/bin:${PATH}"

WORKDIR /app
COPY ./phrazzle_lib ./phrazzle_lib
COPY ./phrazzle ./phrazzle

WORKDIR /app/phrazzle_lib
RUN dart pub get

WORKDIR /app/phrazzle
RUN flutter pub get
RUN flutter build web --release

FROM httpd:latest
COPY --from=build /app/phrazzle/build/web/ /usr/local/apache2/htdocs/
EXPOSE 80